services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./docker_ssl_proxy:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - comments
    networks:
      default:
        aliases:
          - niceorg
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=ABcd1234#
      - SA_USERNAME=sa
      - COMPOSE_HTTP_TIMEOUT=1000
    ports:
      - 1434:1433
  redis:
    container_name: redis
    image: "redis:alpine3.15"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    #command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    #command: ["redis-server", "--bind", "redis", "--port", "6379"]
  nodeapp:
    container_name: nodeapp
    build:
      context: ./ClientApp
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_ACCOUNTS_ENVIRONMENT
      - REACT_APP_GLOBAL_NAV_SCRIPT
      - REACT_APP_GLOBAL_NAV_SCRIPT_IE8
  comments:
    build:
      context: .
      dockerfile: Prod.Dockerfile
    depends_on:
      - database
      - redis
      - nodeapp
    ports:
      - "8080:8080"
    environment:
      - DEFAULT_CONNECTION
      - LOGGING_LOG_FILE_PATH=logs/Serilog-{Date}.json
      - APPSETTINGS_ENVIRONMENT_NAME=DockerTests
      - APPSETTINGS_ENVIRONMENT_SECURESITE=false
      - APPSETTINGS_ENVIRONMENT_REALM=niceorg
      - INDEV_APIKEY
      - INDEV_BASEPATH
      - INDEV_PUBLISHED_CHAPTER
      - INDEV_DRAFT_PREVIEW_CHAPTER
      - INDEV_PUBLISHED_DETAIL
      - INDEV_DRAFT_PREVIEW_DETAIL
      - INDEV_PUBLISHED_PREVIEW_DETAIL
      - INDEV_LIST
      - GILLIAM_CLIENT_CERTIFICATE_BASE64
      - GILLIAM_BASE_PATH
      - GILLIAM_GET_CLAIMS_URL
      - GILLIAM_REALM
      - ENCRYPTION_KEY
      - ENCRYPTION_IV
      - ACCOUNTS_ENVIRONMENT
      - REACT_APP_ACCOUNTS_ENVIRONMENT
      - REACT_APP_GLOBAL_NAV_SCRIPT
      - REACT_APP_GLOBAL_NAV_SCRIPT_IE8
      - WEBAPP_DOMAIN
      - WEBAPP_CLIENTID
      - WEBAPP_CLIENTSECRECT
      - WEBAPP_REDIRECT_URI
      - WEBAPP_LOGOUT_REDIRECT_URI
      - WEBAPP_API_IDENTIFIER
      - WEBAPP_AUTH_SERVICE_URI
      - WEBAPP_GOOGLE_TRACKING_ID
      - ADMINROLE
      - TEAMROLES
      - TEAMROLES1
      - TEAMROLES2
      - TEAMROLES3
      - ORG_COMMENTING
      - CODE_EMAIL1
      - REDIS_CONNECTION_STRING
      - INDEV_IDAM_CONFIG_APIIDENTIFIER
      - INDEV_IDAM_CONFIG_CLIENTID
      - INDEV_IDAM_CONFIG_CLIENTSECRET
      - INDEV_IDAM_CONFIG_DOMAIN
      - AUTH_ADMIN_ID
      - AUTH_ADMIN_ID_5