// flow-typed signature: 08eb70d532cdc924b2aa230b3c6026e6
// flow-typed version: <<STUB>>/aspnet-prerendering_v^3.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aspnet-prerendering'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aspnet-prerendering' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aspnet-prerendering/Prerendering' {
  declare module.exports: any;
}

declare module 'aspnet-prerendering/PrerenderingInterfaces' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aspnet-prerendering/index' {
  declare module.exports: $Exports<'aspnet-prerendering'>;
}
declare module 'aspnet-prerendering/index.js' {
  declare module.exports: $Exports<'aspnet-prerendering'>;
}
declare module 'aspnet-prerendering/Prerendering.js' {
  declare module.exports: $Exports<'aspnet-prerendering/Prerendering'>;
}
declare module 'aspnet-prerendering/PrerenderingInterfaces.js' {
  declare module.exports: $Exports<'aspnet-prerendering/PrerenderingInterfaces'>;
}
