// flow-typed signature: 8e6b145cffce0d039827e7a2ba2dbeee
// flow-typed version: <<STUB>>/@nice-digital/design-system_v^0.4.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nice-digital/design-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nice-digital/design-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nice-digital/design-system/dist/javascripts/modernizr.nice.min' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/dist/javascripts/nice.dev' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/dist/javascripts/nice.min' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/components/in-page-nav/in-page-nav' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/components/in-page-nav/in-page-nav.test' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/components/tabs/tabs' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/components/tabs/tabs.test' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/breakpoints' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/eventr' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/index' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/plugin-autoloader' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/pluginizr' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/tracker' {
  declare module.exports: any;
}

declare module '@nice-digital/design-system/src/javascripts/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nice-digital/design-system/dist/javascripts/modernizr.nice.min.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/dist/javascripts/modernizr.nice.min'>;
}
declare module '@nice-digital/design-system/dist/javascripts/nice.dev.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/dist/javascripts/nice.dev'>;
}
declare module '@nice-digital/design-system/dist/javascripts/nice.min.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/dist/javascripts/nice.min'>;
}
declare module '@nice-digital/design-system/src/components/in-page-nav/in-page-nav.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/components/in-page-nav/in-page-nav'>;
}
declare module '@nice-digital/design-system/src/components/in-page-nav/in-page-nav.test.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/components/in-page-nav/in-page-nav.test'>;
}
declare module '@nice-digital/design-system/src/components/tabs/tabs.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/components/tabs/tabs'>;
}
declare module '@nice-digital/design-system/src/components/tabs/tabs.test.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/components/tabs/tabs.test'>;
}
declare module '@nice-digital/design-system/src/javascripts/breakpoints.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/breakpoints'>;
}
declare module '@nice-digital/design-system/src/javascripts/eventr.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/eventr'>;
}
declare module '@nice-digital/design-system/src/javascripts/index.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/index'>;
}
declare module '@nice-digital/design-system/src/javascripts/plugin-autoloader.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/plugin-autoloader'>;
}
declare module '@nice-digital/design-system/src/javascripts/pluginizr.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/pluginizr'>;
}
declare module '@nice-digital/design-system/src/javascripts/tracker.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/tracker'>;
}
declare module '@nice-digital/design-system/src/javascripts/utils.js' {
  declare module.exports: $Exports<'@nice-digital/design-system/src/javascripts/utils'>;
}
