// flow-typed signature: 0bbbbcfc4f639becb57e27d71b839728
// flow-typed version: <<STUB>>/@nice-digital/eslint-config_v^1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nice-digital/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nice-digital/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nice-digital/eslint-config/es6-flow' {
  declare module.exports: any;
}

declare module '@nice-digital/eslint-config/es6' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nice-digital/eslint-config/es6-flow.js' {
  declare module.exports: $Exports<'@nice-digital/eslint-config/es6-flow'>;
}
declare module '@nice-digital/eslint-config/es6.js' {
  declare module.exports: $Exports<'@nice-digital/eslint-config/es6'>;
}
declare module '@nice-digital/eslint-config/index' {
  declare module.exports: $Exports<'@nice-digital/eslint-config'>;
}
declare module '@nice-digital/eslint-config/index.js' {
  declare module.exports: $Exports<'@nice-digital/eslint-config'>;
}
