// flow-typed signature: ada7fb498f723ead719c34c1a3e9d611
// flow-typed version: <<STUB>>/@nice-digital/icons_v^1.4.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nice-digital/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nice-digital/icons' {
  declare module.exports: any;
}
